### ISSUE TITLE
Start Charging, Start Climate does not work on Kia EV5 (Australia region)

### ISSUE THREAD

**Issue by awesomewilly** [Hyundai-Kia-Connect/hyundai_kia_connect_api#729]
When trying to start actions in Home Assistant integration, "Start charge" and "Start Climate", I get an error, with different error messages.

For Start Charge, I receive an error:

`{'error': 'Access to this API has been disallowed'}`

For Start Climate, I receive the error

`Internal Server Error - Internal Server Error`

Logs attached

[start_charge_error_log.txt](https://github.com/user-attachments/files/18928214/start_charge_error_log.txt)
[start_climate_error_log.txt](https://github.com/user-attachments/files/18928215/start_climate_error_log.txt)

**Comment by cdnninja** [comment]
Please go back and fill the issue template on GitHub.  This is missing key info.

**Comment by bendews** [comment]
I get the same response with my EV5

**Comment by awesomewilly** [comment]
If I get the Android emulator running to check the traffic, I'll respond back here. Hoping someone else has a chance to do so too!

**Comment by rutj87** [comment]
I'm using Home Assistant and find a number of the API service calls fail. Does set charge rate and limit work via this method.

Have a Kia EV5 in AU also.

**Comment by bendews** [comment]
Just had a quick look at starting climate control using iOS and the endpoints & payloads appear to be _**very**_ different:

- Old endpoint:
  `https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/control/engine`
- New endpoint:
  `https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/control/temperature`

Not sure if this is purely due to iOS vs Android (don't see why it would be?) and not sure whether this is affecting all vehicles or is something specific to the EV5 - if so there will need to be some considerable dev effort to branch based on vehicle type & implement the new payloads & endpoints

**Comment by rutj87** [comment]
Are you able to see the end points for the set charge limit and rate?

Also have EV5 and half the service calls don't work.

**Comment by bendews** [comment]
Setting Charge limits doesn't appear to be changed so should still be working, setting AC charge rate is not implemented in the library currently but this is the endpoint & payload:

`https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/charge/chargingcurrent`
`{"chargingCurrent": 2}`

Also start/stop charging endpoints/payload has changed:

Old:
`https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/control/charge`
`{"action":"start"}` or `{"action":"stop"}`

vs

New:
`https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/control/charge`
`{"command":"start"}` or `{"command":"stop"}`

**Comment by cdnninja** [comment]
Ccs support exists for eu which your region is close to a clone of.  It potentially is identical.  Could you compare to the eu code?

**Comment by bendews** [comment]
> Ccs support exists for eu which your region is close to a clone of. It potentially is identical. Could you compare to the eu code?

Looks like they're very similar and could use the same patterns to implement for AU. Start/stop charging is identical, however EU does not have a CCS2 version of Start/Stop Climate whereas the AU one does.

**Comment by rutj87** [comment]
Where are you getting the new end points from?

Would love to work with someone on getting these up and running so can
integrate properly in to my HA setup

**Comment by rutj87** [comment]
Anyone else got the same issues in AUS that would be happy to collaborate to get resolution.

@bendews How did you get end points and payloads

**Comment by cdnninja** [comment]
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/756 moves the EU code up into the API implementation for start and stop charge.  Could someone test?

**Comment by rutj87** [comment]
Does this also fix the set charge rate and charge limit also for AU users/vehicles?

**Comment by cdnninja** [comment]
No, wanting to confirm start stop charge is working first before I spend too much time on it.

**Comment by rutj87** [comment]
Makes sense.


Happy to test but am using via HA.

**Comment by cdnninja** [comment]
Okay let me make it so you can test with HA.  Give me 30 seconds.

**Comment by cdnninja** [comment]
Edit you manifest.json file in HA custom components folder for kia_uvo.   Set the API version to 3.33.1 and restart.   I actually did another merge that should fix charging current as well.

**Comment by rutj87** [comment]
@cdnninja - thanks for working on this!!!

Updated as per below..... but receiving unknown error.  Think I have extracted relevant section from debug logs

![Image](https://github.com/user-attachments/assets/1ed1926e-6e9f-404f-803d-df7caf9f382d)

![Image](https://github.com/user-attachments/assets/f31b76a7-2dea-45c5-afd2-acda0740d5a0)

**Comment by cdnninja** [comment]
Okay try 3.33.2.

**Comment by rutj87** [comment]
@cdnninja good news!! Start/stop charge and Charge current now working.

Set charge limit not working through.

**Comment by cdnninja** [comment]
set charge limits matches EU.  I suspect it hasn't been converted for ccs2 cars.   So that data needs to be sniffed.

**Comment by rutj87** [comment]
@bendews do you have the end point details for Charge limit?

Thanks @cdnninja

**Comment by bendews** [comment]
Here's all the endpoints I thought would be most useful to investigate. Let me know if there's any others I should get. @rutj87 in answer to your question I'm using MITMProxy to sniff the traffic.

### Charge Limits:
`POST https://au-apigw.ccs.kia.com.au:8082/api/v1/spa/vehicles/[VEHICLE_ID]/charge/target`
```
{
    "targetSOClist": [
        {
            "targetSOClevel": 80,
            "plugType": 0
        },
        {
            "targetSOClevel": 70,
            "plugType": 1
        }
    ]
}

```

### Charge Start/Stop:
`POST https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/control/charge`
```
{
    "command": "start"
}

{
    "command": "stop"
}
```

### Climate Start:
`POST https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/control/temperature`
```
{
    "ignitionDuration": 25,
    "command": "start",
    "strgWhlHeating": 1,
    "hvacTempType": 1,
    "hvacTemp": "22.0",
    "sideRearMirrorHeating": 1,
    "drvSeatLoc": "R",
    "seatClimateInfo": {
        "drvSeatClimateState": 4,
        "psgSeatClimateState": 4,
        "rrSeatClimateState": 6,
        "rlSeatClimateState": 6
    },
    "tempUnit": "C",
    "windshieldFrontDefogState": true
}
```

### Climate Stop:
`POST https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/control/temperature`
```
{
    "seatClimateInfo": {
        "drvSeatClimateState": 4,
        "rrSeatClimateState": 6,
        "psgSeatClimateState": 4,
        "rlSeatClimateState": 6
    },
    "command": "stop"
}
```
### V2L Discharge Limit:
`POST https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/charge/dischargelimit`
```
{
    "dischargingLimit": 50
}
```

### Scheduled Climate (Called "Next Departure Time" in app):
`POST https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/reservation/hvac`
```
{
    "reservedHVACInfo1": {
        "reservInfo": {
            "day": [
                1,
                3,
                5
            ],
            "time": {
                "timeSection": 0,
                "time": "0100"
            }
        },
        "reservHVACSet": {
            "airTemp": {
                "value": "24",
                "hvacTempType": 1,
                "unit": 0
            },
            "defrost": false,
            "airCtrl": 1
        },
        "reservHVACflag": 1
    },
    "reservedHVACInfo2": {
        "reservInfo": {
            "day": [
                8
            ],
            "time": {
                "timeSection": 0,
                "time": "1200"
            }
        },
        "reservHVACSet": {
            "airTemp": {
                "value": "24",
                "hvacTempType": 1,
                "unit": 0
            },
            "defrost": false,
            "airCtrl": 1
        },
        "reservHVACflag": 0
    }
}
```

### Charging Schedule
`POST https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/reservation/charge`
```
{
    "reservEndTime": {
        "timeSection": 0,
        "time": "0900"
    },
    "reservFlag": 1,
    "reservStartTime": {
        "timeSection": 0,
        "time": "0800"
    },
    "offpeakPowerFlag": 1
}
```

### Doors Lock/Unlock
`POST https://au-apigw.ccs.kia.com.au:8082/api/v2/spa/vehicles/[VEHICLE_ID]/ccs2/control/door`
```
{
    "command": "open"
}
{
    "command": "close"
}
```

**Comment by cdnninja** [comment]
@rutj87  give 3.33.4 a try and let me know.

**Comment by rutj87** [comment]
@cdnninja - set charge limits now working!!!!

V2L and next departure aren't showing as option in HA services and climate is failing. Vehicle is getting a service atm so will get logs for you tonight for climate.

**Comment by cdnninja** [comment]
https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/1083 is waiting for testing for V2L.

**Comment by bendews** [comment]
@cdnninja would you like me to raise a PR to add the CCS2 start/stop climate support? If so would you like it in `ApiImplType1` or the AU specific implementation? Looks like the CCS2 API is pretty standard across regions for now.

**Comment by cdnninja** [comment]
Go for it!  In the implement file.   I suspect it will fix eu issues too.  

I wouldn't doubt it if we could collapse eu completely with au now but until sure we can stay with this approach.

**Comment by rutj87** [comment]
@cdnninja - here are the errors for start climate and schedule charging/climate

![Image](https://github.com/user-attachments/assets/bb4207f8-7d4f-4b4a-bcc1-3f7fc1d28a6b)

![Image](https://github.com/user-attachments/assets/d5849964-2ea0-423e-922b-23bcb48d2b51)

**Comment by cdnninja** [comment]
Could you try 3.34.5 and let me know?    Are all other actions working beyond V2L?

**Comment by rutj87** [comment]
I couldn't work out why integration wasn't working and noticed you edited the version number! That helps

**Comment by rutj87** [comment]
@cdnninja 

Below are not working:
- schedule charging and climate
- turn on hazard lights
- turn on horn and hazard lights 

Also the integration interface that allows you to adjust ac and dc charge limits doesn't work (but does if you do action via developer tools). Also the lock status doesn't seem to be updating but the lock bottom does work.

Climate start and stop now working.

Let me know if you want me to get error logs for above actions.

**Comment by cdnninja** [comment]
For the hazard and horn and hazard would need dumps from @bendews to solve that. 

For schedule charging I am torn - my code doesn't match the dump but it exists for CCS cars already so not sure if I will break other EU cars by adjusting or if no one else has reported the issue.  Let me sift through issues on kia_uvo to see. 

The interface for charge limits I have seen reports before however those users have struggled to give me what I need to narrow it down.  Logs would be good, also interesting to hear the action works in dev menu.  What error do you get? 

As for lock, that is common because of the scan interval not scanning until after state has switched back.

**Comment by rutj87** [comment]
> For the hazard and horn and hazard would need dumps from [@bendews](https://github.com/bendews) to solve that.
> 
> For schedule charging I am torn - my code doesn't match the dump but it exists for CCS cars already so not sure if I will break other EU cars by adjusting or if no one else has reported the issue. Let me sift through issues on kia_uvo to see.
> 
> The interface for charge limits I have seen reports before however those users have struggled to give me what I need to narrow it down. Logs would be good, also interesting to hear the action works in dev menu. What error do you get?
> 
> As for lock, that is common because of the scan interval not scanning until after state has switched back.

Have attached copy of error when trying to update charge limits from interface. Showing duplicate request error. Have shown have it shows from developer action section for reference.

Regarding the lock, I think it is something else. I have mine refresh regularly and it isn't pulling updated status. Showed with screenshot. Car had been unlocked for hours according to app etc.

Have also included screenshot of error for Schedule_Charging/Climate.

![Image](https://github.com/user-attachments/assets/e8f30e55-c589-41b3-89d8-76a8cd4080a9)
![Image](https://github.com/user-attachments/assets/c044f0a6-781c-4f25-8e9c-c374d91cab50)
![Image](https://github.com/user-attachments/assets/21d3d7c4-1ce6-405d-ab9d-cfeefa434282)
![Image](https://github.com/user-attachments/assets/aa699bf1-1545-439e-b58f-d602b65a16e2)
![Image](https://github.com/user-attachments/assets/d541051c-0124-4428-bb39-54c4c317e90b)

**Comment by cdnninja** [comment]
For the number sliders I just changed them to a box.  I am wondering if is sending it over and over while someone slides it.    Latest kia_uvo release has that update.  Let me know.

**Comment by rutj87** [comment]
> slides

No luck, still throwing the same error.

**Comment by cdnninja** [comment]
Okay would need a full text file debug logs showing the working method vs none to compare.

**Comment by rutj87** [comment]
> Okay would need a full text file debug logs showing the working method vs none to compare.

@cdnninja - here you go :)

Any luck with with the schedule charging?

![Image](https://github.com/user-attachments/assets/1d76b908-d88c-4a87-a57d-9866948e9144)

**Comment by cdnninja** [comment]
I'll need the full logs including the success and the debug statements of what was sent for success and failure.

**Comment by cdnninja** [comment]
I just added another debug statement to set_charge_limits 3.35.1 has this.   I am looking for what folllows: " Set Charge Limits Body" in the successful action call vs failed.

**Comment by rutj87** [comment]
@cdnninja here is the full log.
Made sure to send a successful via developer section and failed attempt by interface

[home-assistant_kia_uvo_2025-04-13T08-53-56.050Z.log](https://github.com/user-attachments/files/19724517/home-assistant_kia_uvo_2025-04-13T08-53-56.050Z.log)

**Comment by cdnninja** [comment]
Was that with 3.35.1? I don't see "set charge limits body" in the file.   Could you also confirm when you get that failure message it didn't work?  I notice it actually isn't failing on setting but rather force updating the car after.

**Comment by cdnninja** [comment]
Also found a bug that would cause you system to force poll the car regularly since the timezone is +10.   I was confused why it was doing a force update after your set command. 

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/770

**Comment by cdnninja** [comment]
Could you test 3.35.2? It should act a bit different for set charge limits.  I haven't got to schedule charge/climate yet.

**Comment by rutj87** [comment]
Have tested 3.35.2 and newest version of the integration but looks like something is broken as integration now not working

![image](https://github.com/user-attachments/assets/74d24726-1454-4722-9239-ede1e962d03c)

**Comment by cdnninja** [comment]
Could I get the full error?

**Comment by rutj87** [comment]
> Could I get the full error?

Here you go.

Re the issue with set charge limits, can confirm it definitely doesn't update even when throws error message.

Re 3.35.1, I think I updated the integration over the top which would have reverted the API change. Sorry.

[home-assistant_kia_uvo_2025-04-13T23-07-37.166Z.log](https://github.com/user-attachments/files/19727773/home-assistant_kia_uvo_2025-04-13T23-07-37.166Z.log)

**Comment by cdnninja** [comment]
Oops 3.35.2 should solve that.

**Comment by rutj87** [comment]
This error was with .2

**Comment by rutj87** [comment]
@cdnninja Integration working again but still throwing same error with setting charge limits via UI

**Comment by cdnninja** [comment]
Oops correct 3.35.3.   Could I get logs of this again?

**Comment by cdnninja** [comment]
With both the successful and failed way of doing it being key.  Last set of logs only seemed to show a single attempt.

**Comment by rutj87** [comment]
> With both the successful and failed way of doing it being key. Last set of logs only seemed to show a single attempt.

Updated logs. Definitely did one of each this time.

![Image](https://github.com/user-attachments/assets/1538dace-2927-47d1-b3bb-acad2c651b11)

[home-assistant_kia_uvo_2025-04-14T02-08-20.406Z.log](https://github.com/user-attachments/files/19728676/home-assistant_kia_uvo_2025-04-14T02-08-20.406Z.log)

**Comment by cdnninja** [comment]
Thank you.  3.35.4 may resolve.

**Comment by rutj87** [comment]
Still same duplicate error on UI with .4

**Comment by cdnninja** [comment]
Have you tried ensuring that both numbers aren't 100? https://www.reddit.com/r/KiaEV9/comments/1jnm88o/cant_charge_to_100/?share_id=AJGWRj8ODmDimhcCDKU0k&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1

**Comment by rutj87** [comment]
Indeed I have. Already have DC set to 70 and trying to adjust AC but still throwing same error.

Let me know if you want updated logs

**Comment by cdnninja** [comment]
Yeah logs would be good. I am running out of ideas.  :)

**Comment by rutj87** [comment]
@cdnninja good luck!

[home-assistant_kia_uvo_2025-04-14T04-07-54.950Z.log](https://github.com/user-attachments/files/19729422/home-assistant_kia_uvo_2025-04-14T04-07-54.950Z.log)

**Comment by cdnninja** [comment]
Are you placing any forced update calls by hand?

**Comment by rutj87** [comment]
> Are you placing any forced update calls by hand?

I have a update that runs every 5 minutes but not 'force update' and still does that same thing when that automation is disabled.

**Comment by cdnninja** [comment]
I released 2.35.12 of kia uvo with a tweak to see if it helps.

**Comment by cdnninja** [comment]
Lock item is fixed in latest API and will be in the next kia_uvo version as well.

**Comment by rutj87** [comment]
@cdnninja Any luck with schedule climate/charge?

**Comment by cdnninja** [comment]
Above in the queries I see a schedule climate and schedule charge as two functions vs one.  In our code we have a single call that combines that.  In your app is it two screens or a single for both?

**Comment by rutj87** [comment]
In HA all in one.

**Comment by cdnninja** [comment]
Yes, but what about the native app?

**Comment by rutj87** [comment]
Scheduled departure, schedule for charging etc all in one screen rest seperate. See attached ![image](https://github.com/user-attachments/assets/eeea7e2d-7062-4ca7-80fd-7f758d54ff6c)

**Comment by cdnninja** [comment]
What's in next departure time? I think that's the service we are working on?

**Comment by rutj87** [comment]
![image](https://github.com/user-attachments/assets/c0d4a3b8-a8fd-49f1-8d60-eb9514e259f4)

**Comment by bendews** [comment]
Here’s scheduled charging too, just for completeness. It’s for syncing up charging with specific off-peak tariffs etc

![Image](https://github.com/user-attachments/assets/abecc7ff-f96c-466d-bf4d-060db55e5881)

**Comment by cdnninja** [comment]
@bendews could you do me a favor and sniff the traffic from the app to see if a "cached call" and "force update" URL is what we are using? I am wondering if we think the cached call update is actually the forced update endpoint for newer cars.

**Comment by bendews** [comment]
Someone from Kia has been following our conversation by the looks of it! New update 2 weeks ago and looks like certificates have now been pinned so we can't mitm the traffic. 

![Image](https://github.com/user-attachments/assets/608feeec-3a01-49a2-ac8d-92b5ca0d9bcc)

**Comment by cdnninja** [comment]
Cert pinning has been around for a few years with EU region.   A few bypass tools exist.

**Comment by zappoo** [comment]
I want to figure out the API calls for window control for KIA AU - i have an android device. How do i do this? Any guide?
